- .github/workflows/build_and_deploy.yaml
- GitHub actions code supports Azure and AWS cloud and the actions
- The actions are triggered only on tag creation
- Following are the list of variables that are required for the actions to run
```
AWS_REGION                                 # AWS region. Example: us-east-2
CLOUD_PROVIDER                             # Cloud provider value. Example: aws OR azure
CURRENT_RELEASE                            # Accepts a list of tags that allow the workflow to run. Example: ["release-1.1.0", "release-1.1.1"]
DEPLOY_REPO                                # Location of the deployment repo. Example: keshavprasadms/obsrv-automation
DEPLOY_REPO_REF                            # Deploy repo branch or tag. Example: main
AWS_TERRAFORM_BACKEND_BUCKET_NAME          # AWS Terraform bucket name. This needs to …
```
> feat: actions build_and_deploy.yaml

- src/app.ts
- src/routes/Router.ts
- src/validators/QueryValidator.ts
Changes -
- Adding query service to app state for it to be globally accessible
> #48 feat: set query service to app state

- Dockerfile
- src/configs/Config.ts
- src/lib/dispatcher/dispatcher.js
- src/lib/envVariables.js
This PR includes:
* increase in the max size of the request
* fixing typos and created new instance for kafka dispatcher
* updated node version in the dockerfile to fix vulnerabilities
> Bug Fixes in Data IN API and fixing vulnerabilities in node version

- api-service/src/services/telemetry.ts
Changes made -
- API setting property to telemetry event was causing issue
- Set function was updated when property doesn't exist
> #90 fix: update telemetry audit event set function

- api-service/src/app.ts
- api-service/src/configs/Config.ts
- api-service/src/data/telemetryActions.ts
- api-service/src/routes/Router.ts
- api-service/src/services/ClientCloudService.ts
- api-service/src/services/DataSourceService.ts
- api-service/src/services/DatasetService.ts
- api-service/src/services/DatasetSourceConfigService.ts
- api-service/src/services/QueryService.ts
- api-service/src/services/telemetry.ts
* Issue #4 feat: enhance the ingest event to add obsrv and source meta
* issue#223: feat: Updated API endpoints with verbs
* issue#223: fix: Test case modification
* issue #84 : fix: API swagger doc update
* #99 fix: upgrade packages to fix vulnerabilities
* Command-service Vulnerabilities fixes (#56)
* Release 1.3.0 into Main (#53)
* issue#223: feat: Updated API endpoints with verbs
* issue#223: fix: Test case modification
* issue #84 : fix: API swagger doc update
* #99 fix: upgrade packages to fix vulnerabilities
---------
* command-service vulnerabilities fixes
---------
* #90 fix: Resolve API Issues (#52)
* #90 fix: format error messages, code cleanup
* #90 fix: validate extraction config during ingest
* #90 fix: add test cases for extraction key validation
* #90 fix: move error …
> Release-1.0.0-GA to Main

- api-service/src/app.ts
- api-service/src/configs/Config.ts
- api-service/src/data/telemetryActions.ts
- api-service/src/routes/Router.ts
- api-service/src/services/ClientCloudService.ts
- api-service/src/services/DataSourceService.ts
- api-service/src/services/DatasetService.ts
- api-service/src/services/DatasetSourceConfigService.ts
- api-service/src/services/QueryService.ts
- api-service/src/services/telemetry.ts
* Issue #4 feat: enhance the ingest event to add obsrv and source meta
* issue#223: feat: Updated API endpoints with verbs
* issue#223: fix: Test case modification
* issue #84 : fix: API swagger doc update
* #99 fix: upgrade packages to fix vulnerabilities
* Command-service Vulnerabilities fixes (#56)
* Release 1.3.0 into Main (#53)
* issue#223: feat: Updated API endpoints with verbs
* issue#223: fix: Test case modification
* issue #84 : fix: API swagger doc update
* #99 fix: upgrade packages to fix vulnerabilities
---------
* command-service vulnerabilities fixes
---------
* #90 fix: Resolve API Issues (#52)
* #90 fix: format error messages, code cleanup
* #90 fix: validate extraction config during ingest
* #90 fix: add test cases for extraction key validation
* #90 fix: move error …
> Rebase develop by release-1.0.1-GA

- api-service/src/app.ts
- api-service/src/configs/Config.ts
- api-service/src/data/telemetryActions.ts
- api-service/src/routes/Router.ts
- api-service/src/services/ClientCloudService.ts
- api-service/src/services/DataSourceService.ts
- api-service/src/services/DatasetService.ts
- api-service/src/services/DatasetSourceConfigService.ts
- api-service/src/services/QueryService.ts
- api-service/src/services/telemetry.ts
* Issue #4 feat: enhance the ingest event to add obsrv and source meta
* issue#223: feat: Updated API endpoints with verbs
* issue#223: fix: Test case modification
* issue #84 : fix: API swagger doc update
* #99 fix: upgrade packages to fix vulnerabilities
* Command-service Vulnerabilities fixes (#56)
* Release 1.3.0 into Main (#53)
* issue#223: feat: Updated API endpoints with verbs
* issue#223: fix: Test case modification
* issue #84 : fix: API swagger doc update
* #99 fix: upgrade packages to fix vulnerabilities
---------
* command-service vulnerabilities fixes
---------
* #90 fix: Resolve API Issues (#52)
* #90 fix: format error messages, code cleanup
* #90 fix: validate extraction config during ingest
* #90 fix: add test cases for extraction key validation
* #90 fix: move error …
> Merge Release-1.0.0-GA (#72) (#73) to opensource branch

- api-service/src/configs/RoutesConfig.ts
- api-service/src/routes/Router.ts
- api-service/src/services/IngestorService.ts
- api-service/src/validators/RequestsValidator.ts
Changes made -
- Add API endpoint to ingest data by tenant id and dataset suffix
> Tenant ingestion

- api-service/src/resources/schemas/DatasourceSaveReq.json
This PR includes:
* Modifying the request validation schema for datasource create API to accept either the ingestion spec or lakehouse if present in the request.
> Issue #304 Modified required fields for datasource create API request

- .github/workflows/codeql.yaml
Configured  the vuln scan for obsrv-api-service repository
> Configure the vuln scan for obsrv-api-service

- api-service/src/resources/schemas/DatasourceSaveReq.json
Reverts Sanketika-Obsrv/obsrv-api-service#112
> Revert "Issue #304 Modified required fields for datasource create API request"

- api-service/src/validators/QueryValidator.ts
This PR includes:
* Modified logic while setting datasource ref incase of lakehouse 
* All unittest cases passed with the fix
* Tested changes in AWS cluster
> Query api fix incase of lakehouse

- api-service/package-lock.json
- api-service/package.json
- api-service/src/v2/configs/Config.ts
- api-service/src/v2/connections/databaseConnection.ts
- api-service/src/v2/connections/kafkaConnection.ts
- api-service/src/v2/controllers/DatasetHealth/DatasetHealth.ts
- api-service/src/v2/controllers/DatasetHealth/DatasetHealthValidationSchema.json
- api-service/src/v2/helpers/ResponseHandler.ts
- api-service/src/v2/routes/Router.ts
- api-service/src/v2/services/HealthService.ts
- api-service/src/v2/services/SystemConfig.ts
- api-service/src/v2/types/DatasetModels.ts
https://sprints.zoho.in/workspace/sanketika#P2/itemdetails/I1/
Following are skipped  and will be taken as new story
infra -  components -> spark, hudi, PV
ingestion  - complete category need to be implemented
query - component -> queriesTimedout
> Dataset Health API

- api-service/src/v2/configs/DatasetConfigDefault.ts
- api-service/src/v2/controllers/DatasetCreate/DatasetCreateValidationSchema.json
- api-service/src/v2/controllers/DatasetStatusTransition/ReadyToPublishSchema.json
- api-service/src/v2/controllers/DatasetUpdate/DatasetUpdateValidationSchema.json
- api-service/src/v2/tests/DatasetManagement/DatasetCreate/Fixtures.ts
- api-service/src/v2/tests/DatasetManagement/DatasetUpdate/Fixtures.ts
- api-service/swagger-doc/openapi_v2.yml
Description
1. Rename file_upload_path to files_upload_path
2. Set props inside dataset_config not required.
> Sanketika-Obsrv/issue-tracker#OBS-151: dataset create and update schema for file_upload_path prop support

- api-service/src/v2/services/CloudServices/AWSStorageService.ts
- Added endpoint. as optional config to support the minio under aws storage service
> #OBS-I58 feat: Minio cloud store support

- command-service/src/command/connector_registry.py
1. Load connector icon byte data as string repr in db; reuse existing icon column
2. retire previous version of connector before making new one live
> Issue #OBS-I144 fix: icon data as string; check default version

- .github/workflows/build_and_deploy.yaml
- api-service/src/services/TableGenerator.ts
**Description:**
1. Cloning the ingestion spec defaults and using because of the cache issue.
> Ingestion spec fix

- api-service/src/app.ts
- api-service/src/configs/Config.ts
- api-service/src/services/otel/OTelService.ts
Added a condition to generate the open telemetry logs/metrics/traces or not.
> Open Telemetry Changes

- api-service/.dockerignore
- api-service/Dockerfile
* #I431: Vuln fix with NodeJs 23
* #I431:  ignored postman collection
* #I431: ignored postman collection
* #I431: removed postman collection
> Vulnerability fixes (#292)

- api-service/src/controllers/QueryWrapper/SqlQueryWrapper.ts
- api-service/src/services/DatasourceService.ts
This pull request provides a wrapper service that retrieves data source information from the PostgreSQL table instead of directly from Druid.
> Superset Datasource Query Wrapper

- api-service/src/configs/Config.ts
- api-service/src/connections/commandServiceConnection.ts
- api-service/src/controllers/ConnectorRegister/ConnectorRegisterController.ts
- api-service/src/controllers/DataAnalyzePII/DataAnalyzePIIController.ts
- api-service/src/controllers/DatasetReset/DatasetReset.ts
- api-service/src/controllers/DatasetStatusTransition/DatasetStatusTransition.ts
- api-service/src/middlewares/userPermissions.json
- api-service/src/routes/Router.ts
- api-service/src/services/DatasetService.ts
1. Data analyse PII API added
2. Update command service endpoints with config
3. Added user token to all the command service calls
> #OBS-I501  - Command service endpoint changes to make them config

- api-service/src/configs/Config.ts
- api-service/src/controllers/DataExhaust/DataExhaustController.ts
**Description:**
1. Defined a telemetry path thats required for the exhaust api as container prefix.
> feat #OBS-I603 : Define telemetry data path for exhaust apis

- command-service/helm-charts/flink-connector/templates/deployment.yaml
- command-service/helm-charts/spark-connector-cron/templates/cronjob.yaml
- command-service/src/command/connector_command.py
- command-service/src/config/service_config.yml
> feat: #ITD-I11 updated command service to pass nodeSelector and securityContext
